### ISSUE TITLE
Conceptual question: can I run sdc on average b0s after registering them, or should I run sdc separately on each ?

### ISSUE THREAD

**Issue by davidrs06** [poldracklab/sdcflows#297]
I have several timepoints, with a DWI sequence containing a single b0 image. I am currently registering all b0s to a common space and using it as input for SDC. Same for T1 images, I register all of them to a common space and use it as input to SDC, along with the transformation to MNI space. Is it ok to proceed like this, or should SDC be run on each T1/b0  pair separately ?

I'm not sure if the distortions will be different depending on the orientation of the patient in the scanner at each timepoint. But if it is the case, registering the b0s to a common space will create a strange mix of distortions in different directions right ?

Thanks in advance for any input !
Best regards,
David

**Comment by effigies** [comment]
I would say it's probably fine to combine within sessions where the subject doesn't leave the scanner, and the head motion is probably reasonably low. Across sessions it seems a bit more tenuous, as a 30deg rotation in the axial plane is plausible and would result in noticeable differences in the direction of the susceptibility artifacts.

The T1w images should be fine to align and average.

**Comment by oesteban** [comment]
> I have several timepoints, with a DWI sequence containing a single b0 image. I am currently registering all b0s to a common space and using it as input for SDC. Same for T1 images, I register all of them to a common space and use it as input to SDC, along with the transformation to MNI space. Is it ok to proceed like this, or should SDC be run on each T1/b0 pair separately ?
> 
> I'm not sure if the distortions will be different depending on the orientation of the patient in the scanner at each timepoint. But if it is the case, registering the b0s to a common space will create a strange mix of distortions in different directions right ?
> 
> Thanks in advance for any input ! Best regards, David

Just to clarify: we are talking about using fieldmap-less correction right? Meaning, you don't have b0s with different encoding directions, correct?

One related aspect is: what is your scanner and what's the session's protocol?

On Siemens and other scanners which automatically re-shim *when needed* unless you stop that, then you should be careful because the fieldmap might be slightly different for the b0s before the re-shimming and after that.

This could happen if your protocol goes like DWI - T1W/T2W - DWI. This is why we normally acquire anatomical sequences at the beginning or end and then put together all EPIs.

On scanners without automatic shimming then this probably is not occurring because otherwise you would've noticed already the DWIs acquired without re-shimming are probably useless.
