### ISSUE TITLE
Dilate fmap and epi masks before coregistration

### ISSUE THREAD

**Issue by psadil** [poldracklab/sdcflows#461]
### What would you like to see added in this software?

With fmriprep, I'm processing data that fairly regularly produces poorly aligned bold and fieldmap images (around 5% of cases, out of ~500). I'm not noticing anything obviously different about the failing cases, though anecdotally it does seem like some scans are more prone to the issue than others. Rerunning the coregistration several times has revealed that it's a pretty variable step. 

One way that seems to reliably improve the coregistration is to heavily dilate the masks, as in, e.g.,

```
$ fslmaths mask.nii.gz -kernel 3D -dilF -dilF -dilF dilated_mask.nii.gz
```

Could mask dilation be included in the [`coeff2epi_wf` workflow](https://github.com/nipreps/sdcflows/blob/1350d57ee0297a3c56342e2b1bf2e5a327a2cb1b/sdcflows/workflows/apply/registration.py#L40)?

### Do you have any interest in helping implement the feature?

Yes

### Additional information / screenshots

This initially started at https://neurostars.org/t/poor-fieldmap-functional-registration-in-fmriprep-highly-variable-step/30397.

Out of the failing data, one participant (4 runs) that could be shared. 

I have a pull request drafted that is more-or-less ready for testing. 

I'd eventually be interested in this change working its way to fmriprep.

**Comment by effigies** [comment]
My concern would be with whether all the different types of fieldmap are as resilient to a dilated mask. This appears to be PEPolar, where the contrasts are going to be extremely similar if not identical between the fieldmap and bold references.

@oesteban Do you have thoughts on this?

**Comment by oesteban** [comment]
I think @psadil's suggestion makes a lot of sense. His idea (if I understand correctly) is to use this mask in the registration between fieldmap reference (magnitude or EPI) and EPI target (DWI, BOLD) --meaning, no downstream use.

An additional issue is that our masking is not very robust (I've been meaning to add synthstrip in the workflow). Even with more dependable masks (e.g., synthstrip), I'd favor this binary dilation.

**Comment by psadil** [comment]
@oesteban , yes that's right -- the proposal is that the existing masks would just be dilated by some amount and not used outside of that coregistration workflow. 

Note that in all cases I've looked at so far, the masks look fine, more-or-less hugging the edge of the brain closely. I currently suspect that the improvement from dilation is due to the additional information provided by allowing for a bit of wiggle room on the boundary of the brain -- so that there are enough "not brain" voxels included within the mask even as slight rotations/translations are considered. Or maybe it's so that the bright voxels near the edge of the brain don't ever leave the mask during rotations/translations? But in general I'd be happy to see synthstrip incorporated :)

@effigies , regarding different types of fieldmaps, I guess the main hope would be that the impact is somewhat lessoned by the use of the MI metric in the coregistration, but I only have pepolar datasets to work with.

**Comment by effigies** [comment]
I'm happy to take y'all's lead on this, but I'm a little curious about the mechanics.

If the issue is that the mask causes some values to be removed from the cost function when the rotation pushes them outside the mask, another approach could be to register masked images and not to pass a mask. Or to mask the images and pass a dilated mask. Both approaches would allow the benefits of masking (not including irrelevant voxels) without incidentally permitting the exclusion of relevant voxels.

**Comment by oesteban** [comment]
In this registration context you mask for two reasons:

(i) - Less voxels to evaluate by the metric
(ii) - Removing structured artifacts in the background that can generate spurious and deep local minima in the cost function

For (i), adding a dilated band around the brain is not going to add a substantial expense. (ii) a dilated mask is not going to change much, especially because the background in MRI is typically just rician noise.

This is to say, we would be better off removing masks completely in this case. When you mask aggressively, you easily remove edges that are invaluable to driving the metric in registration. Masking the images and feeding them into the algorithm will highly likely change the cost function's minima and systematically introduce errors.

This mask is not going to be forwarded into other computations. I'm quite positive @psadil's suggestion will be, in the worst-case scenario, innocuous.

**Comment by effigies** [comment]
Sounds good.

@psadil We have a dilation interface you can use right here: https://github.com/nipreps/sdcflows/blob/1350d57ee0297a3c56342e2b1bf2e5a327a2cb1b/sdcflows/interfaces/brainmask.py#L73-L85

Note that the radius is in voxels, not mm, but I'm pretty sure that's what you were proposing anyway.

**Comment by dc307** [comment]
I think i am having a similar problem and I can see there is a solution using a dilated mask, but I am not sure how I implement it in the fmriprep pipeline. fMRIPrep 24.1.1  Could someone explain please? 

<img width="1401" alt="Image" src="https://github.com/user-attachments/assets/51e6a431-c15c-4a93-8e30-06548067d693" />

**Comment by effigies** [comment]
Have you tried with `nipreps/fmriprep:unstable`? That should include @psadil's fix.

**Comment by dc307** [comment]
I am at the mercy of a IT managed cluster for updates to the (so weeks lead time). Is there anything I can do without upgrading?

**Comment by effigies** [comment]
No. Practically, we can't support mixing and matching versions of dependencies. I would suggest running locally on an affected subject to determine if the issue is resolved.

I hope to release 25.0 in the next two weeks.
